### PR TITLE
Webpack works

### PR DESCRIPTION
**Pull request by megaohms**
to start front end development
`npm run build`
`npm run dev`
resolves issue #2

### CODE REVIEW

**Comment by jwdomingo** [comment]
Is there supposed to be a .babelrc? I am unable to build; see error below:

```
Johns-MacBook-Pro-2:opengallery John$ npm run build

> OpenGallery@1.0.0 build /Users/John/Projects/hackreactor/projects/opengallery
> webpack --watch --config ./config/webpack.config.js

Hash: 9a56cc72acac2de6f40c
Version: webpack 1.12.14
Time: 309ms
    + 1 hidden modules

ERROR in ./client/components/App.js
Module build failed: SyntaxError: /Users/John/Projects/hackreactor/projects/.babelrc: Error while parsing JSON - Unexpected ''
    at JSON5.parse.error (/Users/John/Projects/hackreactor/projects/opengallery/node_modules/json5/lib/json5.js:50:25)
    at JSON5.parse.word (/Users/John/Projects/hackreactor/projects/opengallery/node_modules/json5/lib/json5.js:378:13)
    at JSON5.parse.value (/Users/John/Projects/hackreactor/projects/opengallery/node_modules/json5/lib/json5.js:478:56)
    at Object.parse (/Users/John/Projects/hackreactor/projects/opengallery/node_modules/json5/lib/json5.js:491:18)
    at OptionManager.addConfig (/Users/John/Projects/hackreactor/projects/opengallery/node_modules/babel-core/lib/transformation/file/options/option-manager.js:200:62)
    at OptionManager.findConfigs (/Users/John/Projects/hackreactor/projects/opengallery/node_modules/babel-core/lib/transformation/file/options/option-manager.js:413:16)
    at OptionManager.init (/Users/John/Projects/hackreactor/projects/opengallery/node_modules/babel-core/lib/transformation/file/options/option-manager.js:461:12)
    at File.initOptions (/Users/John/Projects/hackreactor/projects/opengallery/node_modules/babel-core/lib/transformation/file/index.js:194:75)
    at new File (/Users/John/Projects/hackreactor/projects/opengallery/node_modules/babel-core/lib/transformation/file/index.js:123:22)
    at Pipeline.transform (/Users/John/Projects/hackreactor/projects/opengallery/node_modules/babel-core/lib/transformation/pipeline.js:45:16)
    at transpile (/Users/John/Projects/hackreactor/projects/opengallery/node_modules/babel-loader/index.js:14:22)
    at Object.module.exports (/Users/John/Projects/hackreactor/projects/opengallery/node_modules/babel-loader/index.js:88:12)
```

**Comment by jwdomingo** [comment]
Temporarily created my own and was able to build

##### `opengalley/.babelrc`

```
{
  "presets": ["es2015", "react"]
}
```

**Comment by megaohms** [comment]
I haven't seen the .babelrc in any of the tutorials, and wonder how this is different than line 20 of the webpack.config file? also, I would expect .babelrc to need to be in the same directory as the webpack.config file. What is the babelrc file doing?

**Comment by megaohms** [comment]
http://jamesknelson.com/webpack-made-simple-build-es6-less-with-autorefresh-in-26-lines/

**Pull request merged**
